### ISSUE TITLE
Any hope for a fc28 build?

### ISSUE THREAD

**Issue by christofdamian** [alastairgould/minikube-rpm#1]
Same for the kvm2 driver.

**Comment by mr-yaky** [comment]
+1

**Comment by mr-yaky** [comment]
it would be great to use the current versions

**Comment by alastairgould** [comment]
Sorry for the delay. If you still need it, a fc28 package using the latest versions should now be in the repo.

**Comment by christofdamian** [comment]
thanks. I will have a look.
